
package irrgarten.UI;

import irrgarten.Directions;
import irrgarten.GameState;


public class GraphicUI extends javax.swing.JFrame implements UI{
    
    private final Cursors cursor;
    
    
    public GraphicUI() {
        initComponents();
        
        //Contruye con la referencia al JFrame y true que activa el modo modal
        cursor = new Cursors (this, true);
        setVisible(true);
        //ocultamos la etiqueta del ganador
        winnerLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        labyrinth = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        monsters = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        players = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        currentPlayerTextField = new javax.swing.JTextField();
        winnerLabel = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        labyrinth.setEditable(false);
        labyrinth.setBackground(new java.awt.Color(255, 255, 255));
        labyrinth.setColumns(20);
        labyrinth.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labyrinth.setRows(5);
        labyrinth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labyrinth.setFocusable(false);
        jScrollPane1.setViewportView(labyrinth);

        monsters.setEditable(false);
        monsters.setColumns(20);
        monsters.setRows(5);
        monsters.setFocusable(false);
        jScrollPane3.setViewportView(monsters);

        players.setEditable(false);
        players.setColumns(20);
        players.setRows(5);
        players.setFocusable(false);
        jScrollPane4.setViewportView(players);

        log.setEditable(false);
        log.setColumns(20);
        log.setRows(5);
        log.setFocusable(false);
        jScrollPane5.setViewportView(log);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 49, 180));
        jLabel1.setText("CURRENT PLAYER");

        currentPlayerTextField.setEditable(false);
        currentPlayerTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currentPlayerTextField.setText("...");

        winnerLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        winnerLabel.setForeground(new java.awt.Color(251, 111, 146));
        winnerLabel.setText("\"\" ");

        titulo.setFont(new java.awt.Font("Sigmar One", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Irrgarten");
        titulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(176, 196, 222), 1, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 75, 0));
        jLabel2.setText("MONSTERS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 145, 108));
        jLabel3.setText("PLAYERS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(120, 40, 140));
        jLabel4.setText("LOG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(winnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(currentPlayerTextField))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(currentPlayerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(winnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Directions nextMove() {
        return cursor.getDirection();  
    }
    

    @Override
    public void showGame(GameState gameState) {
        
        this.labyrinth.setText(gameState.getLabyrinth());
        this.monsters.setText(gameState.getMonsters());
        this.players.setText(gameState.getPlayers());
        this.log.setText(gameState.getLog());
        
        //forzar el scroll al final del log
        this.log.setCaretPosition(this.log.getDocument().getLength());
        
        this.currentPlayerTextField.setText("Player " + Integer.toString(gameState.getCurrentPlayer()));


        if (gameState.getWinner()) {
            // Mostrar la etiqueta de ganador
            String winnerMessage = "WINNER: ¡Player #" + Integer.toString(gameState.getCurrentPlayer()) + "!";
            this.winnerLabel.setText(winnerMessage);
            this.winnerLabel.setVisible(true);
        }

        repaint(); // Para actualizar la interfaz gráfica
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currentPlayerTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea labyrinth;
    private javax.swing.JTextArea log;
    private javax.swing.JTextArea monsters;
    private javax.swing.JTextArea players;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel winnerLabel;
    // End of variables declaration//GEN-END:variables
}
